USE ROLE SYSADMIN;
USE SCHEMA Air_Quality.STAGING;
CREATE OR REPLACE SECRET Air_Quality_API_Key
  TYPE = GENERIC_STRING
  SECRET_STRING = '*********************************'
  COMMENT = 'API Key for Juhe API - Air Quality Index'
  ;

CREATE OR REPLACE NETWORK RULE Juhe_API_NETWORK_RULE
  TYPE = HOST_PORT
  MODE = EGRESS
  VALUE_LIST = ('hub.juheapi.com');

USE ROLE ACCOUNTADMIN;
  
CREATE OR REPLACE EXTERNAL ACCESS INTEGRATION Juhe_API_ext_access_integration
  ALLOWED_NETWORK_RULES = (Juhe_API_NETWORK_RULE)
  ALLOWED_AUTHENTICATION_SECRETS = (Air_Quality_API_Key)
  ENABLED = true;

GRANT USAGE ON INTEGRATION Juhe_API_ext_access_integration TO ROLE SYSADMIN;
