USE ROLE SYSADMIN;

CREATE TRANSIENT DATABASE IF NOT EXISTS Air_Quality
DATA_RETENTION_TIME_IN_DAYS = 1;

CREATE SCHEMA STAGING;

CREATE SCHEMA HISTORY;

CREATE SCHEMA SILVER;

CREATE SCHEMA GOLD;

-- Verify:

SHOW SCHEMAS IN DATABASE AIR_QUALITY;