USE ROLE SYSADMIN;
USE SCHEMA AIR_QUALITY.HISTORY;

-- Create a permanent table with staging structure + a metadata column.

CREATE OR REPLACE TABLE COUNTRY_CITIES AS
SELECT *, CONVERT_TIMEZONE('UTC', CURRENT_TIMESTAMP()) AS INSERTED_AT_UTC 
FROM AIR_QUALITY.STAGING.COUNTRY_CITIES
WHERE 1=0;

-- VERIFY
DESC TABLE COUNTRY_CITIES;

/*

name	            type	            kind
COUNTRY_NAME	    VARCHAR(16777216)	COLUMN
CITY_NAME	        VARCHAR(16777216)	COLUMN
INSERTED_AT_UTC	    TIMESTAMP_TZ(9)	    COLUMN

*/